### ISSUE TITLE
I keep getting errors

### ISSUE THREAD

**Issue by elieobeid7** [oscarotero/simple-crud#12]
> Item | Color | Size | Quantity | Item Price
> -- | -- | -- | -- | --
> Notice: Undefined index: sold in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Table.php on line 283Warning: Invalid argument supplied for foreach() in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Row.php on line 23Notice: Undefined index: sold in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Table.php on line 283Warning: array_keys() expects parameter 1 to be array, null given in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Table.php on line 39Warning: Invalid argument supplied for foreach() in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Table.php on line 39Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM `sold` WHERE (id > '1') ORDER BY id ASC LIMIT 100' at line 1 in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/SimpleCrud.php:230 Stack trace: #0 /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/SimpleCrud.php(230): PDOStatement->execute(Array) #1 /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Queries/Mysql/Select.php(223): SimpleCrud\SimpleCrud->execute('SELECT FROM `s...', Array) #2 /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/Queries/Mysql/Select.php(81): SimpleCrud\Queries\Mysql\Select->__invoke() #3 /opt/lampp/htdocs/web/emall/production/app/sold_products.php(35): SimpleCrud\Queries\Mysql\Select->run() #4 {main} thrown in /opt/lampp/htdocs/web/emall/production/app/vendor/simple-crud/simple-crud/src/SimpleCrud.php on line 230
> 

For example query is 

```
<td>
  <?php $posts = $db->sold
    ->select()
    ->where('id > :id', [':id' => 1])
    ->orderBy('id ASC')
    ->limit(100)
    ->run();

foreach ($posts as $post) {
    echo $post->id;
} ?>
</td>
```

And one last thing, why can I do, `while (post)` ? I hate foreach loop

**Comment by oscarotero** [comment]
Seems that the table `sold` does not exist.
The variable `$posts` is a array-like object with the result of the query, so `foreach` is the way to iterate with.

**Comment by elieobeid7** [comment]
thank you
