### ISSUE TITLE
How to use typeahead?

### ISSUE THREAD

**Issue by elieobeid7** [oscarotero/simple-crud#19]
I'm sending text using ajax to another file and trying to get results back in typeahead

Without using simple-crud it works

```
	$keyword = strval($_POST['query']);
	$search_param = "{$keyword}%";
	$conn =new mysqli('localhost', 'root', '' , 'diaspora');
	$sql = $conn->prepare("SELECT * FROM company WHERE name LIKE ?");
	$sql->bind_param("s",$search_param);			
 	$sql->execute();
	$result = $sql->get_result(); 
 	if ($result->num_rows > 0) {
		while($row = $result->fetch_assoc()) {
		$companyResult[] = $row["name"];
		}
		echo json_encode($companyResult);
    } 
    
```

Using simple crude it doesn't

```
    $comapny = $db->company->select()
    ->where('name LIKE :keyword', [':keyword' =>$search_param])
    ->run();
    $company = $company->toArray();
    echo $comapny;


```
Also tried converting $company to array and json encoding it, nothing seems to work.

**Comment by oscarotero** [comment]
You forgot to include a `%` at the end of the search param:
```php
 ->where('name LIKE :keyword', [':keyword' => $search_param.'%' ])
```

**Comment by elieobeid7** [comment]
__

**Comment by elieobeid7** [comment]
Is it possible to return everything of the company and not just its name by using the snippet above? I want to do 

`echo $comapny->name . ' ' . $company->address`

**Comment by oscarotero** [comment]
If you want to search using other fields, just add more `where` clauses:

```php
$company = $db->company->select()
    ->where('name LIKE :keyword', [':keyword' =>$search_param.'%'])
    ->orWhere('address LIKE :keyword', [':keyword' =>$search_param.'%'])
    ->run();

//Or just one where:
$company = $db->company->select()
    ->where('name LIKE :keyword OR address LIKE :keyword', [':keyword' =>$search_param.'%'])
    ->run();
```

**Comment by oscarotero** [comment]
If you mean to have a way to return custom values, there's the `setRowMethod` function:

```php
$db->company->setRowMethod('getFullInfo', function () {
    return $company->name.' '.$company->address;
});

$company = $db->company->select()->one()->run();
echo $company->getFullInfo();
```

**Comment by elieobeid7** [comment]
I think I want getFullInfo because I want to search by name and get the related data of my result. Can I use that in search? or do I need to search then use it? So that if you search, it will return the company name like above and the company address

**Comment by oscarotero** [comment]
Ah, got it.
The result of the search returns all data, not only the field you are searching for.

**Comment by elieobeid7** [comment]
I know, how to make it return what I want if possible?

I can do `echo $company` but not `$company->name`, I need specific fields to be displayed in typeahead

**Comment by oscarotero** [comment]
In that case, you have to build the array yourself.

```php
$result = [];

foreach($companies as $company) {
  $result[] = [
    'name' => $company->name,
    'address' => $company->address
  ];
}

echo json_encode($result);
```

**Comment by elieobeid7** [comment]
Sorry for the late reply, I was busy, anyhow that wouldn't work, because the library only gets the name, I just tested it to verify. So it does not search all the data unfortunately, the reason I need the address is because two companies might have the same name in a big multi national database, so the user has to know where the company is located. I also need the id.
