### ISSUE TITLE
inserting multiple input with the same name

### ISSUE THREAD

**Issue by elieobeid7** [oscarotero/simple-crud#26]
I currently do 

`$user = $db->user->create($_POST['data']);`

However I have multiple input with the same name

`      <input type="text" class="form-control" id="mname" name="cdata[name[]]" >`

Can't insert it, do I need to explode it and loop through?

**Comment by oscarotero** [comment]
I'm not sure what do you want to do. If you have a field that can store multiple values, you can define it as json or serialize ([more info here](https://github.com/oscarotero/simple-crud#fields))

**Comment by elieobeid7** [comment]
What I'm trying to do is this: Each time you press add I append a new row of input fields having the same name using jquery, something this

http://jsfiddle.net/jaredwilli/tZPg4/4/

`<input type="text" name="mytext[]">`

and then one would insert it like this

```
$capture_field_vals ="";
if(isset($_POST["mytext"]) && is_array($_POST["mytext"])){
    $capture_field_vals = implode(",", $_POST["mytext"]);   }
$insert_row = $mysqli->query("INSERT INTO table ( example ) VALUES( $capture_field_vals )");
```

but what I want to do is something like this, which might be wrong obviously 

`<input type="text" name="data[mytext[]]">`

So that I could use the trick that you taught me and insert values like this, in a lazy way

`$user = $db->user->create($_POST['data']);`

The whole idea is that the user could keep adding input fields and I have to insert them.

**Comment by oscarotero** [comment]
I think this is something not related with this library, but with your own implementation.
If you want to create multiple rows, just do a forEach of each row:

```php
foreach($_POST['users']) as $data) {
    $user = $db->user->create($data);
    $user->save();
}
```

This library has only one purpose: provide a layer to execute CRUD functions in a database easily. How do you get the data (from html forms, apis, etc) is out of the scope.

**Comment by elieobeid7** [comment]
Last question ever, ever I promise

I have the following html

```
<input type="email" name="cdata[email][]">
<input type="text" name="cdata[phone][]">
```

It looks like this because of [this](https://stackoverflow.com/questions/48136100/is-this-html-input-name-valid-dataexample). Let's insert it, this doesn't work

```
    foreach ($_POST['cdata'] as $cdata) {
        $user = $db->user->create($cdata);
        $user->relate($club);
        $user->save();
    }

```
Nor this

```
   foreach ($_POST['cdata'] as $cdata) {
        foreach ($cdata as $key => $cdata) {
        $user = $db->user->create($cdata[$key]);
        $user->relate($club);
        $user->save();
    }}
```
Nor this

```
foreach ($_POST['cdata'] as $cdata) {
        foreach ($cdata as $key => $cdata) {
            $club = $db->club->create($data); */
       $user = $db->clubMember->create([
            'name' => 'cdata[name]',
            'email' => 'cdata[email]',
            'phone' => 'cdata[phone]',
            'role' => 'cdata[role]'
        ]); 
     $user->relate($club);
    $user->save();
}}

```
Each one of these snippets is giving a different error. How would one insert such data?

**Comment by oscarotero** [comment]
Please, don't make questions unrelated with library. This is about how you create forms and retrieve its data.

Anyway, a way to solve this:

```php
foreach (array_keys($_POST['cdata']['email']) as $key) {
    $db->club->create([
        'name' => $_POST['cdata']['name'][$key],
        'email' => $_POST['cdata']['email'][$key],
        'phone' => $_POST['cdata']['phone'][$key],
        'role' => $_POST['cdata']['role'][$key],
    ]);
}
```
