### ISSUE TITLE
Is it possible to select column names?

### ISSUE THREAD

**Issue by elieobeid7** [oscarotero/simple-crud#27]
Is it possible to select column names from a table, something like

```
SELECT `COLUMN_NAME` 
FROM `INFORMATION_SCHEMA`.`COLUMNS` 
WHERE `TABLE_SCHEMA`='tablename' 
    AND `TABLE_NAME`='tablename';
```

**Comment by oscarotero** [comment]
You can get the full scheme of the database (all tables and columns) with the `getScheme()` method:

```php
$scheme = $db->getScheme();

$fieldsNames = array_keys($scheme['tablename']['fields']);
```

**Comment by elieobeid7** [comment]
'Warning: array_keys() expects parameter 1 to be array, null given'

anyway ill close this issue, coz its not that important, i ended up writing the column names by hand in array. I dont want to waste your time on this one
