### ISSUE TITLE
leftJoin

### ISSUE THREAD

**Issue by iAyubAnsari** [oscarotero/simple-crud#28]
how to execute leftJoin function on select query?

**Comment by oscarotero** [comment]
You only have to add the leftJoin to the select, with the table name and, optionally a condition and mark.

```php
$posts = $db->post->select()
    ->leftJoin('user', 'user.isVisible = :visible', [':visible' => 1])
    ->run();

foreach($posts as $post) {
    echo $post->user;
}
```

**Comment by iAyubAnsari** [comment]
pardon sir, I cant understand that,
how can i execute this :)
$query="SELECT * FROM contact_book LEFT JOIN conversations ON contact_book=id=conversations.contact_id ORDER BY conversations.id DESC";

**Comment by oscarotero** [comment]
To execute raw queries, you can use ` $db->execute($query) `, but I suspect this library is not for you.

**Comment by iAyubAnsari** [comment]
Thank you sir
