### ISSUE TITLE
Add using views for SQLite

### ISSUE THREAD

**Issue by bashopman** [oscarotero/simple-crud#3]
In Queries/Mysql/DbInfo.php method getTables returns both table names and view names, but in Queries/Sqlite/DbInfo.php the same method only returns table names. In order to be able to use views in Sqlite databases, I suggest to change the query used in Queries/Sqlite/DbInfo.php->getTables to:
```sql
SELECT name FROM sqlite_master WHERE type="table" OR type="view"
```
BTW: I like your work for simple-crud!

**Comment by oscarotero** [comment]
Hi, thank you for the suggestion. I didn't know views and sound great.
Looking for information about this, I found that views in sqlite are read-only and in mysql some are updatable, some aren't. So, to support views we need to support also read-only fields (currently all fields are writable). That's not bad, but need a little more work.

**Comment by bashopman** [comment]
I have a use-case for read-only views only, so I didn't think about the difference between SQLite and MySQL...
Thanks for your quick response!

**Comment by oscarotero** [comment]
Hi again.
After some thought, I finally [released a new version](https://github.com/oscarotero/simple-crud/releases/tag/v5.1.3) with your suggestion (and other minor changes). There's no read-only support yet (so if you try to save a view, probably you get a PDO exception) but for your use-case is enought.

**Comment by bashopman** [comment]
Thanks!
