### ISSUE TITLE
How about a little more security?

### ISSUE THREAD

**Issue by PhantomArt** [oscarotero/simple-crud#30]
```
// Oops! SQL Injection!
$db->post->select()->orderBy($_POST['order_by']);
```

I suggest adding a check to the orderBy method. Like that:

```
$fields = $this->table->getFields();
$field = explode(' ', $orderBy, 2)[0];
if (!isset($fields[$field])) {
  throw new \InvalidArgumentException(
    "Invalid field name."
  );
}
```

**Comment by oscarotero** [comment]
Yes, that whould be a good idea. The problem is how to set a other value than a field name. For example: `ORDER BY RAND()`.

**Comment by PhantomArt** [comment]
Well, it seems prudent. Apparently, the best way is to redefine the Select class and define own specific methods, according to a specific task.

**Comment by oscarotero** [comment]
A way to implement this without breaking BC is to create the method `->orderByField($fieldname, $direction)`.
Whant to work in a PR?

**Comment by PhantomArt** [comment]
Sorry, I don't know how to use git, but it's a good idea.

And what about the offset/limit? Apparently the same problem.

**Comment by oscarotero** [comment]
Close this because the new version allows to set fields safely with this method:

```php
$query->orderBy((string) $db->table->name);
```
