### ISSUE TITLE
Undefined index: post

### ISSUE THREAD

**Issue by logaro** [oscarotero/simple-crud#32]
Hi, i've used the exact code of sample
But i'm getting this errors:
what's wrong?

```

Notice: Undefined index: post in /Table.php on line 283

Warning: Invalid argument supplied for foreach() in /Row.php on line 23

Notice: Undefined index: post in /Table.php on line 283

Warning: array_keys() expects parameter 1 to be array, null given in /Table.php on line 39

Warning: Invalid argument supplied for foreach() in /Table.php on line 39

```

**Comment by oscarotero** [comment]
The code in readme is not tested, it's only to explain the api and features of the library. Anyway, It seems like you don't have a database with the same scheme defined in readme (`post`, `category`, `tag` and `post_tag` tables)
