### ISSUE TITLE
Fatal error: Declaration of SimpleCrud\EventDispatcher\Dispatcher::dispatch(SimpleCrud\EventDispatcher\object $event)

### ISSUE THREAD

**Issue by bavamca** [oscarotero/simple-crud#37]
Fatal error: Declaration of SimpleCrud\EventDispatcher\Dispatcher::dispatch(SimpleCrud\EventDispatcher\object $event) must be compatible with Psr\EventDispatcher\EventDispatcherInterface::dispatch(Psr\EventDispatcher\object $event) in /curd/vendor/simple-crud/simple-crud/src/EventDispatcher/Dispatcher.php on line 7

Can you able to let me know, How to solve the above issue?

**Comment by oscarotero** [comment]
What is your php version?

**Comment by bavamca** [comment]
Php Version 7.2

**Comment by oscarotero** [comment]
I just commited a change. Could you please test it before release the patch version?

**Comment by bavamca** [comment]
OK 
Let me check it

**Comment by bavamca** [comment]
Working fine thank you

**Comment by oscarotero** [comment]
Ok, version 7.4.1 released. Thank you
