### ISSUE TITLE
How to use join query?

### ISSUE THREAD

**Issue by bavamca** [oscarotero/simple-crud#38]
Any reference is available for join query?

**Comment by oscarotero** [comment]
Join is documented in README (https://github.com/oscarotero/simple-crud#query-api)

You can use the `join()` and `catJoin()` methods from [Atlas.php](http://atlasphp.io/cassini/query/select.html):

```php
$db->post->select()
    ->join('LEFT', 'category', 'category.id = post.category_id');
```

Or the `joinRelation()` method that detects automatically the relation:

```php
$db->post->select()
    ->joinRelation($db->category)
```

**Comment by bavamca** [comment]
Works fine thank you **oscarotero**
