### ISSUE TITLE
Query log?

### ISSUE THREAD

**Issue by ilsenem** [oscarotero/simple-crud#4]
It there any way to log queries without modifying sources or is planned for future versions?

P.S. Thanks for a great tool! :+1:

**Comment by oscarotero** [comment]
I use [php-debugbar](https://github.com/maximebf/php-debugbar) that provides a [PDO data collector](https://github.com/maximebf/php-debugbar/tree/master/src/DebugBar/DataCollector/PDO) to this, but it's a good idea to have a simple way to store and return the queries. I'll work on that.
Thank you.

**Comment by oscarotero** [comment]
I've implemented the function `onExecute`, to provide a callback allowing to debug the queries just after execute them. For example:

```php
$db->onExecute(function ($pdo, $statement, $marks) {
    var_dump([
        'query' => $statement->queryString,
        'data' => $marks
    ]);
});
```

**Comment by eusonlito** [comment]
I think that is more useful an internal query log (disabled by default) like Eloquent ORM (enabled with enabledQueryLog and retrieved with getQueryLog).

Useful to automated queries catch, group processing, analyse outside main code, etc...

**Comment by oscarotero** [comment]
I thought this too, but this allows that and provides more flexibility.
For example, you can log the queries using any logger library:
```php
$db->onExecute(function ($pdo, $statement, $marks) {
    Logger::log($statement->queryString);
});
```
And you can choose what you want to save, and even use some useful functions of `PDOStatement` like `debugDumpParams`. Collecting internally all statements, queries, etc increase the memory used. This way allows to save the info in a stream (for example).
