### ISSUE TITLE
the update method is not working

### ISSUE THREAD

**Issue by raphxsc** [oscarotero/simple-crud#41]
Table    offsetSet 
Workarround

            $this->update($value)
                //->columns()
                ->where('id = ', $offset)
                ->run();
            return new Row($this,$value);

**Comment by oscarotero** [comment]
Hi.
Good catch! Thank you for reporting this.
I had to change the return type of this method to `void` in order to cover all possible cases (for example, if no row exists): c3ac81f0899c5d7d4ea2c612a0de702b127455fd
