### ISSUE TITLE
Compare two floats column incorrect

### ISSUE THREAD

**Issue by darkvovich** [oscarotero/simple-crud#46]
| Status  | Sum  (float) | Paid  (float) |
|---------|----------|------------------|
| 0          | 115627  | 115627             |

```
$whereArr = [];
$whereArr['status] = 0;
$whereArr[] = "paid > 0 AND paid >= sum";
$query = $db->orders->select()->whereEquals($whereArr)->get();
```
This example of compare two float fields return empty.

**Comment by oscarotero** [comment]
This is not a problem of simple-crud, but something related with mysql.
See this issue: https://stackoverflow.com/questions/2567434/mysql-floating-point-comparison-issues
Perhaps, instead of float you should use decimal for these fields.

**Comment by darkvovich** [comment]
Thx
