### ISSUE TITLE
How to convert Result Object to Array values?

### ISSUE THREAD

**Issue by darkvovich** [oscarotero/simple-crud#48]
Any simple way to convert Key - Value Obj of select result to simple array without keys?

My difficult solution was:
1. get items
`$getItems = $db->staff_departments->select()->orderBy('name ASC')->limit(50)->get();`
2. convert to array
`$array = json_decode(json_encode($getItems), true);`
3. remove keys
`$result = array_values($array);`

**Comment by oscarotero** [comment]
You can use `toArray()` for that. It still return the keys but you can use `array_values`:

```php
$result = array_values($getItems->toArray());
```

**Comment by darkvovich** [comment]
Thx!
