### ISSUE TITLE
orWhereSprintf return error

### ISSUE THREAD

**Issue by darkvovich** [oscarotero/simple-crud#49]
This works good:
`$db->staff->select()->whereSprintf('firstname LIKE %s', '%'.$user_name.'%')->orderBy('id DESC')->limit(5)->get();`
But when adding orWhereSprintf
`$db->staff->select()->whereSprintf('firstname LIKE %s', '%'.$user_name.'%')->orWhereSprintf('lastname LIKE %s', '%'.$user_name.'%')->orderBy('id DESC')->limit(5)->get();`
 return error
```
Fatal error: Uncaught BadMethodCallException: The method "orWhereSprintf" is not valid in ...
#2 {main} thrown in /libs/vendor/simple-crud/simple-crud/src/Queries/Query.php on line 25
```

**Comment by oscarotero** [comment]
Fixed in 7.5.3. Thanks!
