### ISSUE TITLE
About LEFT JOIN

### ISSUE THREAD

**Issue by niltonmeloba** [oscarotero/simple-crud#5]
Hi Guys,
How I can to make a INNER JOIN between two tables or more?

**Comment by oscarotero** [comment]
Currently INNER JOIN is not supported (just LEFT JOIN), so I suggest two options:

* Create a pull request with this feature (you can use the [left-join code](https://github.com/oscarotero/simple-crud/blob/master/src/Queries/Mysql/Select.php#L172) as a basis). Maybe it's good idea to create a method like `->join($table, $on = null, $type = 'LEFT')` that can be reused by `leftJoin`, `innerJoint`, etc...
* Or create your own `Select` class including this feature like this:

```php
namespace App\CustomQueries;

class Select extends \SimpleCrud\Queries\Mysql\Select
{
    public function innerJoin()
    {
        //here your code
        return $this;
    }
}


//Register this namespace to use this query instead the default
$queryFactory = $simpleCrud->getQueryFactory();

$queryFactory->addNamespace('App\\CustomQueries\\');

//Ready
$simpleCrud->table->select()->innerJoin('otherTable')->run();
```

**Comment by niltonmeloba** [comment]
Ok, Thks Oscar

**Comment by oscarotero** [comment]
I've added the new method `join` to allow to use any join type, for example:

```php
$table->select()->join('INNER', 'otherTable')->run();
```

It's not tagged yet, but you can use the dev-master version.
