### ISSUE TITLE
Remove property?

### ISSUE THREAD

**Issue by seahorsepip** [oscarotero/simple-crud#6]
I have the following code api code that uses simple-crud:
```
$app->get("/user", function ($request, $response) {
    $user = $this->db->user[$_SESSION["id"]];
    $user->password = null;
    return $response->withJson($user);
});
```

Which returns the following JSON:
`{"id":1,"email":"seahorsepip@outlook.com","password":null,"name":"Thomas Gladdines"}`

But I want the following JSON:
`{"id":1,"email":"seahorsepip@outlook.com","name":"Thomas Gladdines"}`

So I thought the following might work:
```
$app->get("/user", function ($request, $response) {
    $user = $this->db->user[$_SESSION["id"]];
    unset($user->password);
    return $response->withJson($user);
});
```

But it doesn't, probably because the object attribute's are just like in RedBean [virtual](http://stackoverflow.com/questions/5359083/remove-a-member-from-an-object) so to solve this RedBean has a removeProperty method. 

Any chance there is a similar solution for this library?

**Comment by oscarotero** [comment]
A solution for this is get first the values as an array:

```php
$app->get("/user", function ($request, $response) {
    $user = $this->db->user[$_SESSION["id"]]->toArray();
    unset($user['password']);
    return $response->withJson($user);
});
```

**Comment by seahorsepip** [comment]
Thanks I didn't know about the toArray() method.


Of topic but I assume there is no IDE helper for php storm? I would be great to get autocompletion.

**Comment by oscarotero** [comment]
No, there's no IDE helper (I don't use php storm)
